/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 08 23:20:57 GMT 2020
 */

package com.github.jazzmuesli.jacevo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.jazzmuesli.jacevo.Calculator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.divide(0.0, 3117.0100827049373);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.divide(1.0, (-497.5670355));
      assertEquals((-0.0020097794440805555), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.add(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.add(850.1137478, (-1347.6807833));
      assertEquals((-497.5670355), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.divide(4503.2127745596, 1749.076);
      assertEquals(2.574623843995115, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.add(1749.076, 1456.3936827049372);
      assertEquals(3205.4696827049374, double0, 0.01);
  }
}
